### ISSUE TITLE
index.html not being updated on build

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/AMR-Bibliography#201]
Hence, the webpage is out of date relative to the data.

**Comment by nschneid** [comment]
Apparently the build (generating HTML from CSV) used to happen with Travis, but no longer.

Using https://docs.github.com/en/actions/quickstart, I created a GitHub action: see .github/workflows/build-bib.yml.

Now on each push, it runs this. But I don't think the generated index.html is getting committed. https://joht.github.io/johtizen/build/2022/01/20/github-actions-push-into-repository.html Example 1 may be a good model for doing this.

**Comment by nschneid** [comment]
I think this is fixed with 590c312

Shira, could you try adding an entry to see if it builds correctly?

Note that a build failure will be triggered if a change to the repo does not affect the generated HTML file. I think that's OK.

**Comment by shirawein** [comment]
I added a paper and the previous commit showed up on the HTML page (html is still not being added upon commit but only upon successive commit).
